# Generated by Django 5.0.6 on 2024-09-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='strava_activity_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
