# Generated by Django 5.0.6 on 2024-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='waist_circumference',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
