# Generated by Django 5.0.6 on 2024-09-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_alter_activity_strava_activity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.FloatField(),
        ),
    ]
