# Generated by Django 5.0.6 on 2024-07-16 21:04

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_profile_date_of_birth_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_of_residency',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
