# Generated by Django 5.0.6 on 2024-09-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_alter_activity_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
